### ISSUE TITLE
feature/fix-backend

### ISSUE THREAD

**Issue by hardergeorge** [cs361-W16/Group03#32]
Once this ticket is implemented the Aces Up game will have a working backend.

At the end of Assignment 1 we had a merge conflict preventing the final piece of the game to be added to our group repo. In addition we have made a design decision that will require changes to one of our classes. This means that there are several pieces of our backend that need to be changed and fixed for the game to work.

**Comment by armatasc** [comment]
Thanks for fixing the backend merge issues, George! Great work
